import { z } from "zod";

export const LeadResultSchema = z.object({
  id: z.number(),
  quiz_id: z.string(),
  user_data: z.object({
    name: z.string().nullable(),
    email: z.string().nullable(),
    phone: z.string().nullable(),
    address: z.string().nullable(),
  }),
  total_score: z.number(),
  result_page_id: z.string().nullable(),
  share_link: z.string().nullable(),
  ip_address: z.string().nullable(),
  user_agent: z.string().nullable(),
  started_at: z.string().nullable(),
  completed_at: z.string().nullable(),
  time_spent: z.string().nullable(),
  quiz: z.object({
    id: z.number(),
    uuid: z.string(),
    name: z.string(),
    title: z.string().nullable(),
    description: z.string().nullable(),
    landing_page_text: z.string().nullable(),
    logo: z.string().nullable(),
    background_image: z.string().nullable(),
    primary_color: z.string().nullable(),
    secondary_color: z.string().nullable(),
    embed_code: z.string().nullable(),
    is_active: z.boolean(),
    views: z.string().nullable(),
    created_at: z.string().nullable(),
    updated_at: z.string().nullable(),
    client_id: z.number().nullable(),
    heading: z.string().nullable(),
    cta_text: z.string().nullable(),
    submit_button_text: z.string().nullable(),
    result_button_text: z.string().nullable(),
    questions: z.array(
      z.object({
        id: z.number(),
        quiz_id: z.string(),
        question_text: z.string(),
        image: z.string().nullable(),
        order: z.number(),
        is_active: z.boolean(),
        created_at: z.string(),
        updated_at: z.string(),
        multiselect: z.boolean(),
        answers: z.array(
          z.object({
            id: z.number(),
            question_id: z.string(),
            answer_text: z.string(),
            points: z.number(),
            order: z.number(),
            created_at: z.string(),
            updated_at: z.string(),
          }),
        ),
      }),
    ),
  }),
  resultPage: z
    .object({
      id: z.number(),
      quiz_id: z.string(),
      title: z.string(),
      content: z.string().nullable(),
      image: z.string().nullable(),
      min_score: z.number().nullable(),
      max_score: z.number().nullable(),
      order: z.number(),
      created_at: z.string(),
      updated_at: z.string(),
    })
    .nullable(),
  answers: z.array(
    z.object({
      id: z.number(),
      quiz_submission_id: z.string(),
      question_id: z.string(),
      answer_id: z.string(),
      points_earned: z.number(),
      created_at: z.string(),
      updated_at: z.string(),
    }),
  ),
});

export type TLeadResultSchema = z.infer<typeof LeadResultSchema>;
