/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as AppQuizzesCreateIndexRouteImport } from './routes/_app/quizzes/create/index'
import { Route as AppQuizzesIdViewIndexRouteImport } from './routes/_app/quizzes/$id/view/index'
import { Route as AppQuizzesIdStatisticsIndexRouteImport } from './routes/_app/quizzes/$id/statistics/index'
import { Route as AppQuizzesIdSettingsIndexRouteImport } from './routes/_app/quizzes/$id/settings/index'
import { Route as AppQuizzesIdResultPagesIndexRouteImport } from './routes/_app/quizzes/$id/result-pages/index'
import { Route as AppQuizzesIdQuestionsIndexRouteImport } from './routes/_app/quizzes/$id/questions/index'
import { Route as AppQuizzesIdLeadsIndexRouteImport } from './routes/_app/quizzes/$id/leads/index'
import { Route as AppQuizzesIdEditIndexRouteImport } from './routes/_app/quizzes/$id/edit/index'
import { Route as AppQuizzesIdResultPagesCreateIndexRouteImport } from './routes/_app/quizzes/$id/result-pages/create/index'
import { Route as AppQuizzesIdQuestionsCreateIndexRouteImport } from './routes/_app/quizzes/$id/questions/create/index'
import { Route as AppQuizzesIdResultPagesViewIdRouteImport } from './routes/_app/quizzes/$id/result-pages/view/$id'
import { Route as AppQuizzesIdResultPagesEditIdRouteImport } from './routes/_app/quizzes/$id/result-pages/edit/$id'
import { Route as AppQuizzesIdQuestionsQuestionIDEditIndexRouteImport } from './routes/_app/quizzes/$id/questions/$questionID/edit/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppQuizzesCreateIndexRoute = AppQuizzesCreateIndexRouteImport.update({
  id: '/quizzes/create/',
  path: '/quizzes/create/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuizzesIdViewIndexRoute = AppQuizzesIdViewIndexRouteImport.update({
  id: '/quizzes/$id/view/',
  path: '/quizzes/$id/view/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuizzesIdStatisticsIndexRoute =
  AppQuizzesIdStatisticsIndexRouteImport.update({
    id: '/quizzes/$id/statistics/',
    path: '/quizzes/$id/statistics/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppQuizzesIdSettingsIndexRoute =
  AppQuizzesIdSettingsIndexRouteImport.update({
    id: '/quizzes/$id/settings/',
    path: '/quizzes/$id/settings/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppQuizzesIdResultPagesIndexRoute =
  AppQuizzesIdResultPagesIndexRouteImport.update({
    id: '/quizzes/$id/result-pages/',
    path: '/quizzes/$id/result-pages/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppQuizzesIdQuestionsIndexRoute =
  AppQuizzesIdQuestionsIndexRouteImport.update({
    id: '/quizzes/$id/questions/',
    path: '/quizzes/$id/questions/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppQuizzesIdLeadsIndexRoute = AppQuizzesIdLeadsIndexRouteImport.update({
  id: '/quizzes/$id/leads/',
  path: '/quizzes/$id/leads/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuizzesIdEditIndexRoute = AppQuizzesIdEditIndexRouteImport.update({
  id: '/quizzes/$id/edit/',
  path: '/quizzes/$id/edit/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuizzesIdResultPagesCreateIndexRoute =
  AppQuizzesIdResultPagesCreateIndexRouteImport.update({
    id: '/quizzes/$id/result-pages/create/',
    path: '/quizzes/$id/result-pages/create/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppQuizzesIdQuestionsCreateIndexRoute =
  AppQuizzesIdQuestionsCreateIndexRouteImport.update({
    id: '/quizzes/$id/questions/create/',
    path: '/quizzes/$id/questions/create/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppQuizzesIdResultPagesViewIdRoute =
  AppQuizzesIdResultPagesViewIdRouteImport.update({
    id: '/quizzes/$id/result-pages/view/$id',
    path: '/quizzes/$id/result-pages/view/$id',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppQuizzesIdResultPagesEditIdRoute =
  AppQuizzesIdResultPagesEditIdRouteImport.update({
    id: '/quizzes/$id/result-pages/edit/$id',
    path: '/quizzes/$id/result-pages/edit/$id',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppQuizzesIdQuestionsQuestionIDEditIndexRoute =
  AppQuizzesIdQuestionsQuestionIDEditIndexRouteImport.update({
    id: '/quizzes/$id/questions/$questionID/edit/',
    path: '/quizzes/$id/questions/$questionID/edit/',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/quizzes/create': typeof AppQuizzesCreateIndexRoute
  '/quizzes/$id/edit': typeof AppQuizzesIdEditIndexRoute
  '/quizzes/$id/leads': typeof AppQuizzesIdLeadsIndexRoute
  '/quizzes/$id/questions': typeof AppQuizzesIdQuestionsIndexRoute
  '/quizzes/$id/result-pages': typeof AppQuizzesIdResultPagesIndexRoute
  '/quizzes/$id/settings': typeof AppQuizzesIdSettingsIndexRoute
  '/quizzes/$id/statistics': typeof AppQuizzesIdStatisticsIndexRoute
  '/quizzes/$id/view': typeof AppQuizzesIdViewIndexRoute
  '/quizzes/$id/result-pages/edit/$id': typeof AppQuizzesIdResultPagesEditIdRoute
  '/quizzes/$id/result-pages/view/$id': typeof AppQuizzesIdResultPagesViewIdRoute
  '/quizzes/$id/questions/create': typeof AppQuizzesIdQuestionsCreateIndexRoute
  '/quizzes/$id/result-pages/create': typeof AppQuizzesIdResultPagesCreateIndexRoute
  '/quizzes/$id/questions/$questionID/edit': typeof AppQuizzesIdQuestionsQuestionIDEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/quizzes/create': typeof AppQuizzesCreateIndexRoute
  '/quizzes/$id/edit': typeof AppQuizzesIdEditIndexRoute
  '/quizzes/$id/leads': typeof AppQuizzesIdLeadsIndexRoute
  '/quizzes/$id/questions': typeof AppQuizzesIdQuestionsIndexRoute
  '/quizzes/$id/result-pages': typeof AppQuizzesIdResultPagesIndexRoute
  '/quizzes/$id/settings': typeof AppQuizzesIdSettingsIndexRoute
  '/quizzes/$id/statistics': typeof AppQuizzesIdStatisticsIndexRoute
  '/quizzes/$id/view': typeof AppQuizzesIdViewIndexRoute
  '/quizzes/$id/result-pages/edit/$id': typeof AppQuizzesIdResultPagesEditIdRoute
  '/quizzes/$id/result-pages/view/$id': typeof AppQuizzesIdResultPagesViewIdRoute
  '/quizzes/$id/questions/create': typeof AppQuizzesIdQuestionsCreateIndexRoute
  '/quizzes/$id/result-pages/create': typeof AppQuizzesIdResultPagesCreateIndexRoute
  '/quizzes/$id/questions/$questionID/edit': typeof AppQuizzesIdQuestionsQuestionIDEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_app/quizzes/create/': typeof AppQuizzesCreateIndexRoute
  '/_app/quizzes/$id/edit/': typeof AppQuizzesIdEditIndexRoute
  '/_app/quizzes/$id/leads/': typeof AppQuizzesIdLeadsIndexRoute
  '/_app/quizzes/$id/questions/': typeof AppQuizzesIdQuestionsIndexRoute
  '/_app/quizzes/$id/result-pages/': typeof AppQuizzesIdResultPagesIndexRoute
  '/_app/quizzes/$id/settings/': typeof AppQuizzesIdSettingsIndexRoute
  '/_app/quizzes/$id/statistics/': typeof AppQuizzesIdStatisticsIndexRoute
  '/_app/quizzes/$id/view/': typeof AppQuizzesIdViewIndexRoute
  '/_app/quizzes/$id/result-pages/edit/$id': typeof AppQuizzesIdResultPagesEditIdRoute
  '/_app/quizzes/$id/result-pages/view/$id': typeof AppQuizzesIdResultPagesViewIdRoute
  '/_app/quizzes/$id/questions/create/': typeof AppQuizzesIdQuestionsCreateIndexRoute
  '/_app/quizzes/$id/result-pages/create/': typeof AppQuizzesIdResultPagesCreateIndexRoute
  '/_app/quizzes/$id/questions/$questionID/edit/': typeof AppQuizzesIdQuestionsQuestionIDEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/quizzes/create'
    | '/quizzes/$id/edit'
    | '/quizzes/$id/leads'
    | '/quizzes/$id/questions'
    | '/quizzes/$id/result-pages'
    | '/quizzes/$id/settings'
    | '/quizzes/$id/statistics'
    | '/quizzes/$id/view'
    | '/quizzes/$id/result-pages/edit/$id'
    | '/quizzes/$id/result-pages/view/$id'
    | '/quizzes/$id/questions/create'
    | '/quizzes/$id/result-pages/create'
    | '/quizzes/$id/questions/$questionID/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/quizzes/create'
    | '/quizzes/$id/edit'
    | '/quizzes/$id/leads'
    | '/quizzes/$id/questions'
    | '/quizzes/$id/result-pages'
    | '/quizzes/$id/settings'
    | '/quizzes/$id/statistics'
    | '/quizzes/$id/view'
    | '/quizzes/$id/result-pages/edit/$id'
    | '/quizzes/$id/result-pages/view/$id'
    | '/quizzes/$id/questions/create'
    | '/quizzes/$id/result-pages/create'
    | '/quizzes/$id/questions/$questionID/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/reset-password/'
    | '/_app/quizzes/create/'
    | '/_app/quizzes/$id/edit/'
    | '/_app/quizzes/$id/leads/'
    | '/_app/quizzes/$id/questions/'
    | '/_app/quizzes/$id/result-pages/'
    | '/_app/quizzes/$id/settings/'
    | '/_app/quizzes/$id/statistics/'
    | '/_app/quizzes/$id/view/'
    | '/_app/quizzes/$id/result-pages/edit/$id'
    | '/_app/quizzes/$id/result-pages/view/$id'
    | '/_app/quizzes/$id/questions/create/'
    | '/_app/quizzes/$id/result-pages/create/'
    | '/_app/quizzes/$id/questions/$questionID/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/quizzes/create/': {
      id: '/_app/quizzes/create/'
      path: '/quizzes/create'
      fullPath: '/quizzes/create'
      preLoaderRoute: typeof AppQuizzesCreateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quizzes/$id/view/': {
      id: '/_app/quizzes/$id/view/'
      path: '/quizzes/$id/view'
      fullPath: '/quizzes/$id/view'
      preLoaderRoute: typeof AppQuizzesIdViewIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quizzes/$id/statistics/': {
      id: '/_app/quizzes/$id/statistics/'
      path: '/quizzes/$id/statistics'
      fullPath: '/quizzes/$id/statistics'
      preLoaderRoute: typeof AppQuizzesIdStatisticsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quizzes/$id/settings/': {
      id: '/_app/quizzes/$id/settings/'
      path: '/quizzes/$id/settings'
      fullPath: '/quizzes/$id/settings'
      preLoaderRoute: typeof AppQuizzesIdSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quizzes/$id/result-pages/': {
      id: '/_app/quizzes/$id/result-pages/'
      path: '/quizzes/$id/result-pages'
      fullPath: '/quizzes/$id/result-pages'
      preLoaderRoute: typeof AppQuizzesIdResultPagesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quizzes/$id/questions/': {
      id: '/_app/quizzes/$id/questions/'
      path: '/quizzes/$id/questions'
      fullPath: '/quizzes/$id/questions'
      preLoaderRoute: typeof AppQuizzesIdQuestionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quizzes/$id/leads/': {
      id: '/_app/quizzes/$id/leads/'
      path: '/quizzes/$id/leads'
      fullPath: '/quizzes/$id/leads'
      preLoaderRoute: typeof AppQuizzesIdLeadsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quizzes/$id/edit/': {
      id: '/_app/quizzes/$id/edit/'
      path: '/quizzes/$id/edit'
      fullPath: '/quizzes/$id/edit'
      preLoaderRoute: typeof AppQuizzesIdEditIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quizzes/$id/result-pages/create/': {
      id: '/_app/quizzes/$id/result-pages/create/'
      path: '/quizzes/$id/result-pages/create'
      fullPath: '/quizzes/$id/result-pages/create'
      preLoaderRoute: typeof AppQuizzesIdResultPagesCreateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quizzes/$id/questions/create/': {
      id: '/_app/quizzes/$id/questions/create/'
      path: '/quizzes/$id/questions/create'
      fullPath: '/quizzes/$id/questions/create'
      preLoaderRoute: typeof AppQuizzesIdQuestionsCreateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quizzes/$id/result-pages/view/$id': {
      id: '/_app/quizzes/$id/result-pages/view/$id'
      path: '/quizzes/$id/result-pages/view/$id'
      fullPath: '/quizzes/$id/result-pages/view/$id'
      preLoaderRoute: typeof AppQuizzesIdResultPagesViewIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quizzes/$id/result-pages/edit/$id': {
      id: '/_app/quizzes/$id/result-pages/edit/$id'
      path: '/quizzes/$id/result-pages/edit/$id'
      fullPath: '/quizzes/$id/result-pages/edit/$id'
      preLoaderRoute: typeof AppQuizzesIdResultPagesEditIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quizzes/$id/questions/$questionID/edit/': {
      id: '/_app/quizzes/$id/questions/$questionID/edit/'
      path: '/quizzes/$id/questions/$questionID/edit'
      fullPath: '/quizzes/$id/questions/$questionID/edit'
      preLoaderRoute: typeof AppQuizzesIdQuestionsQuestionIDEditIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppQuizzesCreateIndexRoute: typeof AppQuizzesCreateIndexRoute
  AppQuizzesIdEditIndexRoute: typeof AppQuizzesIdEditIndexRoute
  AppQuizzesIdLeadsIndexRoute: typeof AppQuizzesIdLeadsIndexRoute
  AppQuizzesIdQuestionsIndexRoute: typeof AppQuizzesIdQuestionsIndexRoute
  AppQuizzesIdResultPagesIndexRoute: typeof AppQuizzesIdResultPagesIndexRoute
  AppQuizzesIdSettingsIndexRoute: typeof AppQuizzesIdSettingsIndexRoute
  AppQuizzesIdStatisticsIndexRoute: typeof AppQuizzesIdStatisticsIndexRoute
  AppQuizzesIdViewIndexRoute: typeof AppQuizzesIdViewIndexRoute
  AppQuizzesIdResultPagesEditIdRoute: typeof AppQuizzesIdResultPagesEditIdRoute
  AppQuizzesIdResultPagesViewIdRoute: typeof AppQuizzesIdResultPagesViewIdRoute
  AppQuizzesIdQuestionsCreateIndexRoute: typeof AppQuizzesIdQuestionsCreateIndexRoute
  AppQuizzesIdResultPagesCreateIndexRoute: typeof AppQuizzesIdResultPagesCreateIndexRoute
  AppQuizzesIdQuestionsQuestionIDEditIndexRoute: typeof AppQuizzesIdQuestionsQuestionIDEditIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppQuizzesCreateIndexRoute: AppQuizzesCreateIndexRoute,
  AppQuizzesIdEditIndexRoute: AppQuizzesIdEditIndexRoute,
  AppQuizzesIdLeadsIndexRoute: AppQuizzesIdLeadsIndexRoute,
  AppQuizzesIdQuestionsIndexRoute: AppQuizzesIdQuestionsIndexRoute,
  AppQuizzesIdResultPagesIndexRoute: AppQuizzesIdResultPagesIndexRoute,
  AppQuizzesIdSettingsIndexRoute: AppQuizzesIdSettingsIndexRoute,
  AppQuizzesIdStatisticsIndexRoute: AppQuizzesIdStatisticsIndexRoute,
  AppQuizzesIdViewIndexRoute: AppQuizzesIdViewIndexRoute,
  AppQuizzesIdResultPagesEditIdRoute: AppQuizzesIdResultPagesEditIdRoute,
  AppQuizzesIdResultPagesViewIdRoute: AppQuizzesIdResultPagesViewIdRoute,
  AppQuizzesIdQuestionsCreateIndexRoute: AppQuizzesIdQuestionsCreateIndexRoute,
  AppQuizzesIdResultPagesCreateIndexRoute:
    AppQuizzesIdResultPagesCreateIndexRoute,
  AppQuizzesIdQuestionsQuestionIDEditIndexRoute:
    AppQuizzesIdQuestionsQuestionIDEditIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
