/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as AppQuizzesIndexRouteImport } from './routes/_app/_quizzes/index'
import { Route as AppQuizzesQuizzesCreateIndexRouteImport } from './routes/_app/_quizzes/quizzes/create/index'
import { Route as AppQuizzesQuizzesViewIdRouteImport } from './routes/_app/_quizzes/quizzes/view/$id'
import { Route as AppQuizzesQuizzesEditIdRouteImport } from './routes/_app/_quizzes/quizzes/edit/$id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppQuizzesIndexRoute = AppQuizzesIndexRouteImport.update({
  id: '/_quizzes/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuizzesQuizzesCreateIndexRoute =
  AppQuizzesQuizzesCreateIndexRouteImport.update({
    id: '/_quizzes/quizzes/create/',
    path: '/quizzes/create/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppQuizzesQuizzesViewIdRoute = AppQuizzesQuizzesViewIdRouteImport.update({
  id: '/_quizzes/quizzes/view/$id',
  path: '/quizzes/view/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuizzesQuizzesEditIdRoute = AppQuizzesQuizzesEditIdRouteImport.update({
  id: '/_quizzes/quizzes/edit/$id',
  path: '/quizzes/edit/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppQuizzesIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/quizzes/edit/$id': typeof AppQuizzesQuizzesEditIdRoute
  '/quizzes/view/$id': typeof AppQuizzesQuizzesViewIdRoute
  '/quizzes/create': typeof AppQuizzesQuizzesCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppQuizzesIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/quizzes/edit/$id': typeof AppQuizzesQuizzesEditIdRoute
  '/quizzes/view/$id': typeof AppQuizzesQuizzesViewIdRoute
  '/quizzes/create': typeof AppQuizzesQuizzesCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/_quizzes/': typeof AppQuizzesIndexRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_app/_quizzes/quizzes/edit/$id': typeof AppQuizzesQuizzesEditIdRoute
  '/_app/_quizzes/quizzes/view/$id': typeof AppQuizzesQuizzesViewIdRoute
  '/_app/_quizzes/quizzes/create/': typeof AppQuizzesQuizzesCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/quizzes/edit/$id'
    | '/quizzes/view/$id'
    | '/quizzes/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/quizzes/edit/$id'
    | '/quizzes/view/$id'
    | '/quizzes/create'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/_quizzes/'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/reset-password/'
    | '/_app/_quizzes/quizzes/edit/$id'
    | '/_app/_quizzes/quizzes/view/$id'
    | '/_app/_quizzes/quizzes/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/_quizzes/': {
      id: '/_app/_quizzes/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppQuizzesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_quizzes/quizzes/create/': {
      id: '/_app/_quizzes/quizzes/create/'
      path: '/quizzes/create'
      fullPath: '/quizzes/create'
      preLoaderRoute: typeof AppQuizzesQuizzesCreateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_quizzes/quizzes/view/$id': {
      id: '/_app/_quizzes/quizzes/view/$id'
      path: '/quizzes/view/$id'
      fullPath: '/quizzes/view/$id'
      preLoaderRoute: typeof AppQuizzesQuizzesViewIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_quizzes/quizzes/edit/$id': {
      id: '/_app/_quizzes/quizzes/edit/$id'
      path: '/quizzes/edit/$id'
      fullPath: '/quizzes/edit/$id'
      preLoaderRoute: typeof AppQuizzesQuizzesEditIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppQuizzesIndexRoute: typeof AppQuizzesIndexRoute
  AppQuizzesQuizzesEditIdRoute: typeof AppQuizzesQuizzesEditIdRoute
  AppQuizzesQuizzesViewIdRoute: typeof AppQuizzesQuizzesViewIdRoute
  AppQuizzesQuizzesCreateIndexRoute: typeof AppQuizzesQuizzesCreateIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppQuizzesIndexRoute: AppQuizzesIndexRoute,
  AppQuizzesQuizzesEditIdRoute: AppQuizzesQuizzesEditIdRoute,
  AppQuizzesQuizzesViewIdRoute: AppQuizzesQuizzesViewIdRoute,
  AppQuizzesQuizzesCreateIndexRoute: AppQuizzesQuizzesCreateIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
